Evie-Skinner18/happy_hacktoberfest_19

css/styles.css

Added a gradient background compatible with all browsers.

Modified background color

---

css/styles.css
index.html

I changed some styles of the header.

Changed the styles of header in website

---

css/styles.css
index.html

Added the progress bars with animations

Added progress bars

---

index.html

Added icons

---

index.html

adding to the explanation that the project was carried out from all over the world

Add 'From...' heading to index.html

---

css/styles.css
index.html

I thought this would look nice. :)

Rainbow Gradient Header

---

contributing.md

- Added Contributors List to contributing.md and contributors so far.
This addresses #12 
- There were some styling issues that were auto-corrected by prettier.

Added List of Contributors

---

css/styles.css

Fixes issue 39 - https://github.com/Evie-Skinner18/happy_hacktoberfest_19/issues/39

Fixed broken UI - Issue #39

---

css/styles.css
index.html

https://github.com/Evie-Skinner18/happy_hacktoberfest_19/pull/32

Update branch from #32

---

css/styles.css

Hey this is my first PR, hope i made it right ?! Thanks for the Project btw. :)

change the Background-color of the countdown

---

css/styles.css
index.html
js/scripts.js

- Replace the H1 tag with H2 for semantic purposes.
- Add colour to seconds section alone.

Style the countdown timer section

---

index.html

The github button on the navbar is now functional and it allows the users to visit the github repository.

Github button

---

index.html

The punctuations that I added are actually not necessary. But definitely the changes are harmless and also make the site look richer...

Correct some spelling errors and punctuations

---

Contributing Guidelines.md
Contributors.md
PR_Template.md
README.md

Updated documents, added instructions for contributors, created new files.
Closes #81

Updated documents

---

Contributors.md
contributors.html
contributors.json
index.html

This branch will add a new contributor's page to the website.
Changes made are as follows:
- Created contributors.html
- Created contributors.json
- Added Link to Navbar

Added Contributor's page

---

beachtime.html
css/beachtime.css

lots of room for improvement in the css and html for playing around.

Added a beach animation page to play with

---

about.html
beachtime.html
bouncing-ball-effect.html
contributors.html
css/styles.css
index.html

Merged vale-c's PR and also removed all the Bootstrap containers from the navbar on each page. Also removed navbar links that lead nowhere and added a button on beachtime.html that takes the user back home

Vale c css changes

---

css/styles.css

Simple CSS fix to add spacing to the gray row in the homepage.

Adjusted spacing in gray row homepage

---

about.html
css/styles.css
index.html

Fixed merge conflicts from countdown timer change. Tried to change the text colour of timer to yellow but not working. Removed some redundant/commented out code

Soniella countdown timer

---

css/styles.css
index.html

Countdown timer as well as header look cooler now!

Made countdown timer look cooler

---

css/styles.css
index.html
js/scripts.js

Changed the Color of Count down Timer

Color Changes

---

css/styles.css
index.html

I did some text effects on the heading tags for fun.
Happy hacktoberfest!

added some text effects

---

Contributors.md
beer.html
css/beer.css
js/beer.js

i love beer page added
Issue #176

Issue 176: i love beer page

---

Contributors.md
css/styles.css
index.html

Should I add this as an issue to add the remaining branches?

Create a git workflow branch called, "features"

---

Contributors.md

Hi Dibby- please accept my pull wequest!

Added my name to contributors list

---

contributors.html

This PR makes the list under "Why Hacktoberfest is awesome" clearer by capitalizing the first word of each line and adding a colon.

Update to "Why Hacktoberfest is awesome" list

---

about.html

added link to github page on about.html @Evie-Skinner18

updated link to github

---

index.html
js/jsbat.js

He agregado un murciélago al website.

Hola buenas tardes, he agregado un murciélago al website. Saludos!

---

index.html

Do you want it to be located in the nav-bar or in the events-drohdown?

added halloween page to event dropdown

---

Contributing Guidelines.md

This closes #210

---

beer.html
css/beer.css

saw an issue on navlink and add design #176

---

index.html

Change so all three images have hover captions

Change so all three images have hover captions

---

css/beachtime.css

Reposition the button and make it actually clickable

Fixes #223

---

index.html

Added a link to dayofdead.html in the navbar as the issue stated

Added day of dead link

---

index.html

This html change restricts the dropdown box from gaining margin on hover for the largest element in the box

Updated html to stop css error

---

index.html

helping with issue #7 Add features everyone!

added link to github projects

---

competition.html
css/competitions.css

Style changes to form on competitions page, small style fixes

---

about.html
pages/k-kaufmann.html

Cleanup nav links in about and k-kaufmann page.

Fix nav links in about and k-kaufmann

---

halloween.html
js/halloween.js

Clean up halloween code and separate js from html file.

Add lantern toggle off and on

---

Contributors.md
js/halloween.js

Fixs issue that lantern doesn't toggle on /halloween

---

README.md
about.html

Absolute first-timers like myself usually don't know how to make a pull request. Added a brief description of the process to the readme file.

How to pull
